import fs from 'fs';
import { join } from 'path';

import { getTranslationKeys } from './traverseTranslations';

let s = `
// this is autogenerated by running \`npm run gen:i18:keys\`
export type TranslationKeys =
`;

fs.readdirSync(join(__dirname, '../public/locales/en')).forEach((file) => {
  const data = fs.readFileSync(join(__dirname, '../public/locales/en', file), {
    encoding: 'utf-8',
  });
  const english = JSON.parse(data);
  const keys = getTranslationKeys(english);
  if (keys.length) {
    s += `
    | ${getTranslationKeys(english)
      .map((k) => `  "${k}"`)
      .join('|\n')}
      `;
  }
});

fs.writeFileSync(join(__dirname, '../src/generated/translationKeys.ts'), s);
